# Generated by Django 4.2.1 on 2023-05-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_per', models.IntegerField(primary_key=True, serialize=False)),
                ('pas_per', models.CharField(max_length=30)),
                ('nom_per', models.CharField(max_length=30)),
                ('ape_per', models.CharField(max_length=30)),
                ('tel_per', models.IntegerField()),
                ('dir_per', models.CharField(max_length=30)),
                ('cat_per', models.CharField(max_length=2)),
                ('vig_per', models.DateField()),
                ('dep_per', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
