# Generated by Django 4.2.2 on 2023-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperacionalesm',
            name='fec_pre',
            field=models.DateField(null=True),
        ),
    ]
