# Generated by Django 3.1.7 on 2023-05-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id_dep', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_dep', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dependencias',
            },
        ),
        migrations.CreateModel(
            name='Soat',
            fields=[
                ('id_soa', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_exp_soa', models.DateField(null=True)),
                ('fec_ven_soa', models.DateField(null=True)),
            ],
            options={
                'db_table': 'soat',
            },
        ),
        migrations.CreateModel(
            name='Tecnicomecanica',
            fields=[
                ('id_tec', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_exp_tec', models.DateField(null=True)),
                ('fec_ven_tec', models.DateField(null=True)),
            ],
            options={
                'db_table': 'tecnicomecanica',
            },
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='vig_per',
            field=models.DateField(null=True),
        ),
    ]
