# Generated by Django 3.1.7 on 2023-05-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20230523_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_per',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
