# Generated by Django 4.2.2 on 2023-07-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_preoperacionalesm_fec_pre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preoperacionalesc',
            fields=[
                ('id_pre', models.AutoField(primary_key=True, serialize=False)),
                ('dir_del_pre', models.CharField(max_length=20)),
                ('dir_tra_pre', models.CharField(max_length=20)),
                ('sis_luc_pre', models.CharField(max_length=20)),
                ('luc_fre_pre', models.CharField(max_length=20)),
                ('luc_rev_pre', models.CharField(max_length=20)),
                ('luc_par_pre', models.CharField(max_length=20)),
                ('vpan_pre', models.CharField(max_length=20)),
                ('vlat_pre', models.CharField(max_length=20)),
                ('vtra_pre', models.CharField(max_length=20)),
                ('limp_pre', models.CharField(max_length=20)),
                ('elat_pre', models.CharField(max_length=20)),
                ('eret_pre', models.CharField(max_length=20)),
                ('pit_pre', models.CharField(max_length=20)),
                ('odo_pre', models.CharField(max_length=20)),
                ('gas_pre', models.CharField(max_length=20)),
                ('tem_pre', models.CharField(max_length=20)),
                ('cin_pre', models.CharField(max_length=20)),
                ('alar_pre', models.CharField(max_length=20)),
                ('cha_pue_pre', models.CharField(max_length=20)),
                ('pue_cie_pre', models.CharField(max_length=20)),
                ('esc_acc_pre', models.CharField(max_length=20)),
                ('pas_tec_pre', models.CharField(max_length=20)),
                ('ven_eme_pre', models.CharField(max_length=20)),
                ('alc_vol_pre', models.CharField(max_length=20)),
                ('fre_pri_pre', models.CharField(max_length=20)),
                ('fre_man_pre', models.CharField(max_length=20)),
                ('agu_lim_pre', models.CharField(max_length=20)),
                ('agu_ref_pre', models.CharField(max_length=20)),
                ('ace_mot_pre', models.CharField(max_length=20)),
                ('liq_fre_pre', models.CharField(max_length=20)),
                ('liq_bat_pre', models.CharField(max_length=20)),
                ('ace_hid_pre', models.CharField(max_length=20)),
                ('cor_pre', models.CharField(max_length=20)),
                ('man_pre', models.CharField(max_length=20)),
                ('est_lla_pre', models.CharField(max_length=20)),
                ('pre_lla_pre', models.CharField(max_length=20)),
                ('lab_lla_pre', models.CharField(max_length=20)),
                ('rep_lla_pre', models.CharField(max_length=20)),
                ('señ_eme_pre', models.CharField(max_length=20)),
                ('tac_pre', models.CharField(max_length=20)),
                ('cha_pre', models.CharField(max_length=20)),
                ('gat_pre', models.CharField(max_length=20)),
                ('gua_pre', models.CharField(max_length=20)),
                ('cru_pre', models.CharField(max_length=20)),
                ('her_pre', models.CharField(max_length=20)),
                ('bot_pre', models.CharField(max_length=20)),
                ('ext_pre', models.CharField(max_length=20)),
                ('obs_pre', models.CharField(max_length=300)),
                ('fec_pre', models.DateField(null=True)),
                ('pla_pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'preoperacionalesc',
            },
        ),
    ]
