# Generated by Django 3.1.7 on 2023-05-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20230524_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='id_dep',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
