# Generated by Django 4.2.2 on 2023-07-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_preoperacionalesc_taco_pre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preoperacionalesc',
            name='taco_pre',
            field=models.CharField(max_length=20),
        ),
    ]
