# Generated by Django 3.1.7 on 2023-05-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20230524_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dep_per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.dependencias'),
        ),
    ]
