# Generated by Django 4.2.1 on 2023-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_preoperacionalesc_taco_pre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='pase_per',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
