# Generated by Django 4.2.1 on 2023-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_usuarios_pase_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='pase_per',
            new_name='pase_ade_per',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pase_atr_per',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
