# Generated by Django 4.2.1 on 2023-08-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_rename_pase_per_usuarios_pase_ade_per_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soat',
            name='fec_vig_soa',
            field=models.DateField(null=True),
        ),
    ]
