# Generated by Django 3.1.7 on 2023-05-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20230524_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='id_dep',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dep_per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.dependencias'),
        ),
    ]
