# Generated by Django 3.1.7 on 2023-05-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20230524_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='id_dep',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
