# Generated by Django 4.2.1 on 2023-08-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_soat_fec_vig_soa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_man', models.AutoField(primary_key=True, serialize=False)),
                ('fec_man', models.DateField(null=True)),
                ('tipo_man', models.CharField(max_length=20)),
                ('des_obs_man', models.CharField(max_length=500)),
                ('per_man', models.CharField(max_length=50)),
                ('rec_man', models.CharField(max_length=200)),
                ('id_veh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
    ]
