# Generated by Django 3.1.7 on 2023-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20230524_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dep_per',
            field=models.IntegerField(),
        ),
    ]
