# Generated by Django 3.1.7 on 2023-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20230526_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prue',
            fields=[
                ('id_prue', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_exp_tec', models.DateField(null=True)),
                ('fec_ven_tec', models.DateField(null=True)),
            ],
            options={
                'db_table': 'prue',
            },
        ),
    ]
