# Generated by Django 3.1.7 on 2023-05-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_prue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('pla_veh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('num_lic_veh', models.BigIntegerField()),
                ('cla_veh', models.CharField(max_length=50)),
                ('mar_veh', models.CharField(max_length=50)),
                ('mod_veh', models.IntegerField()),
                ('col_veh', models.CharField(max_length=30)),
                ('num_mot_veh', models.CharField(max_length=50)),
                ('num_cha_veh', models.CharField(max_length=50)),
                ('cil_veh', models.IntegerField()),
                ('tip_car_veh', models.CharField(max_length=50)),
                ('est_veh', models.BooleanField()),
                ('obs_veh', models.CharField(max_length=200)),
                ('dep_veh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.dependencias')),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehiculosAsignados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ing', models.DateTimeField()),
                ('fec_sal', models.DateTimeField(null=True)),
                ('obs_veh_asi', models.CharField(max_length=200)),
                ('id_per', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.usuarios')),
                ('id_veh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'vehiculos_asignados',
            },
        ),
        migrations.DeleteModel(
            name='Prue',
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='per_asi_veh',
            field=models.ManyToManyField(blank=True, through='panel.VehiculosAsignados', to='panel.Usuarios'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='soa_veh',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.soat'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='tec_veh',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.tecnicomecanica'),
        ),
    ]
