# Generated by Django 3.1.7 on 2023-05-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20230531_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soat',
            name='id_soa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tecnicomecanica',
            name='id_tec',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
