# Generated by Django 3.1.7 on 2023-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_auto_20230601_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='obs_veh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
