# Generated by Django 4.2.2 on 2023-07-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_auto_20230609_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='dep_veh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.dependencias'),
        ),
        migrations.AlterField(
            model_name='vehiculosasignados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Preoperacionalesm',
            fields=[
                ('id_pre', models.AutoField(primary_key=True, serialize=False)),
                ('niv_pre', models.CharField(max_length=20)),
                ('dir_pre', models.CharField(max_length=20)),
                ('gua_pre', models.CharField(max_length=20)),
                ('cha_pre', models.CharField(max_length=20)),
                ('sus_pre', models.CharField(max_length=20)),
                ('fre_pre', models.CharField(max_length=20)),
                ('lla_pre', models.CharField(max_length=20)),
                ('rin_pre', models.CharField(max_length=20)),
                ('tre_pre', models.CharField(max_length=20)),
                ('exo_pre', models.CharField(max_length=20)),
                ('ret_pre', models.CharField(max_length=20)),
                ('man_pre', models.CharField(max_length=20)),
                ('luc_pre', models.CharField(max_length=20)),
                ('dir_stop_pre', models.CharField(max_length=20)),
                ('pit_pre', models.CharField(max_length=20)),
                ('obs_pre', models.CharField(max_length=300)),
                ('pla_veh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'preoperacionalesm',
            },
        ),
    ]
