# Generated by Django 4.2.2 on 2023-07-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_rename_pla_veh_preoperacionalesm_pla_pre'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperacionalesm',
            name='man_mec_pre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
