# Generated by Django 4.2.2 on 2023-07-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_alter_preoperacionalesm_man_mec_pre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preoperacionalesm',
            new_name='Preoperacionalesmotos',
        ),
        migrations.AlterModelTable(
            name='preoperacionalesmotos',
            table='preoperacionalesmotos',
        ),
    ]
